{{- $jaeger := .Values.infra.jaeger -}}
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    {{- include "crys.labels" . | nindent 4 }}
    {{- include "crys.selectorLabels" "jaeger" | nindent 4 }}
spec:
  selector:
    {{- include "crys.selectorLabels" "jaeger" | nindent 4 }}
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    {{- include "crys.labels" . | nindent 4 }}
    {{- include "crys.selectorLabels" "jaeger" | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "crys.selectorLabels" "jaeger" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crys.labels" . | nindent 8 }}
        {{- include "crys.selectorLabels" "jaeger" | nindent 8 }}
    spec:
      containers:
        - name: jaeger
          image: {{ $jaeger.image }}
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            periodSeconds: 10
            failureThreshold: 5
